
/**/var Lang={'close_page_until_webi':'This page will be available after you watch the introductory webinar!',
'lang_errorLoadFile':'An error during the downloading file!',
'NextPrompt':'Further',
'close':'Close',
'popup_box_loading':'Loading ...',
'access_denied':'The access to the section is prohibited for not authorized users',
'close_page_closed_for':'This page is available only to users with an access level',
'copyed':'Copied',
'copy':'Copy',
'success_copy':'Successfully copied to the Clipboard',
'add_favorite':'Press \"Ctrl + D\" to add the page to Favorites.',
'maps_scheme':'The scheme of directions',
'sitegide_zap_kont_info':'Fill out the contact information in your personal cabinet',
'sitegide_zap_more_det':'Fill out this form with as much detail as possible',
'want_start_gid':'Do you want to go through a brief training by the system?',
'yes':'Yes',
'No':'No',
'yes_delete':'Yes, delete it!',
'yes_ban':'Yes, block it!',
'timer_day':'d.',
'timer_hr':'an hour',
'timer_min':'min',
'timer_sec':'SEC',
'save':'Save',
'attention':'Attention!',
'loading':'Load',
'success':'Successfully',
'a_ns_not_found':'Records are not found',
'a_ns_not_found_a':'The record [#value] is not found',
'domain_is_bad':'There was pointed out incorrect domain or domain zone is not supported',
'set_domain':'Enter the domain address',
'success_domain_connect':'Domain successfully connected, sites begin to open on it within a certain time',
'sucess':'successfully',
'nitice_message_sended':'The text message has been sent successfully ',
'tema_realy_change_sponsor':'Are you sure you want to change the sponsor?',
'Ok':'OK',
'pages_set_checked':'Mark this material as studied?',
'pages_access_denied':'Access is denied',
'pages_access_prev_current':'Training takes place in steps, first learn the material on this page.',
'pages_access_prev_first':'Training takes place in steps, first learn the previous material.',
'pages_access_to_group':'The page is available for users from the group not lower than:',
'settings_set_roylty_payment':'Specify the way of withdrawal',
'settings__del_event':'Delete an event?',
'settings_add_photo':'Add an image',
'settings__del_record':'Delete the recording?',
'settings__exp_record':'Create a page?',
'settings_generel_menu_saved':'Successfully',
'settings_generel_menu_saved_text':'Menu settings saved successfully, the changes will come into force after you refresh the page.',
'settings_success_domain_connect':'Domain successfully connected, the site starts to open on it within a certain time',
'settings_general_new_menu':'New section',
'settings_general_level':'Level',
'account_uploading':'Loading',
'account_change_photo':'Change photo',
'account_sponsor_was_found':'The sponsor has been found! You can register',
'account_sponsor_not_found':'The sponsor is not found',
'account_sponsor_search_again':'Do you have ideas where we can look for?',
'account_sponsor_ok_go_reg':'Then register without a sponsor, we will try to find it later',
'account_need-sponsor_data':'Fill at least one field in the search form',
'account_verify_del_quest':'Are you sure you want to delete this verification?',
'account_messages_delall_ask':'Deleting the correspondence',
'account_messages_delall_text':'Are you sure you want to delete all correspondence?',
'order_domain_error_dot':'You cannot use the address point. An address ending (.ru,. COM, etc), select on the right',
'team_verify_confirme':'Are you sure you want to verify the user?',
'team_verify_rejecte':'Are you sure you want to reject the application?',
'team_change_sponsor_desc':'Changes refer to all partners for this user',
'team_success_change_sponsor':'You have successfully changed the sponsor!',
'team_change_sponsor':'Change the curator',
'events_allready_zap':'You recorded',
'events_suc_reg_webinar':'You have successfully registered',
'events_suc_reg_webinar_text':'We\'ll send you a link for the Webinar in 30 minutes before the beginning.',
'events_suc_reg_life_text':'We will send you all the necessary information on your email. Add to your calendar this event',
'events_copy_own_link':'In the meantime, copy this link: ',
'events_allready_inwebi':'You have already signed up for the webinar',
'chat_rearly_send_paymes':'Are you sure you want to send the notification fee?',
'chat_message_sended':'The message was sent',
'chat_rearly_clear_chat':'Clear the chat?',
'chat_geting_pass_for_vebinar':'Get a password for the webinar...',
'chat_pass_for_webinar':'The webinar password: [#pass]',
'chat_you_kiked_out':'You got kicked out of the room!',
'chat_deleting_user':'Deleting a user',
'chat_are_you_shure_for_del_user':'Are you sure that you want to kick the user out of the room?',
'chat_banimg_user':'Ban user',
'chat_disbanimg_user':'Unlock the user',
'chat_are_you_shure_for_ban_user':'Are you sure that you want to block the ability to send messages to the user?',
'chat_shure_disban_user':'Are you sure that you want to unlock a user?',
'chat_yes_disban':'Yes, unlock!',
'chat_is_baned':'Chatroom is blocked',
'chat_you_was_baned':'You have been blocked!',
'chat_you_cant_write':'You can no longer write in the chat!',
'chat_is_off':'Chat is off',
'chat_start_speaker':'Do you want to be a speaker at this webinar?',
'chat_lateenter':'Come next time and don\'t be late more than 5 minutes!',
'chat_dont_flood_please':'Do not flood please!',
'trafic_add_fon':'Add a background',
'trafic__realdelbg':'Delete the selected background?',
'trafic_realydelland':'Are you sure that you want to remove the landing?',
'trafic_realyclone':'Clone the landing?',
'trafic_noname':'Untitled',
'trafic_realysetdef':'Do you really want to make landing by default?',
'trafic_realysetfor_all':'Do you really want to make landing for everyone?',
'trafic_set_landing_to_alllp':'Are you sure that you want to set this domain to all landings?',
'balance_realy_want_accept':'Do you confirm the withdrawal of money to the user?',
'balance_do_send_balance':'Are you sure you want to send resources?',
'balance_success_sendbalance':'You have successfully transferred the resources!',
'leads_plset_task':'Specify the task',
'leads_dtneedmorenow':'Specify the time later in future',
'leads_plset_datetime':'Specify the date and time of the next contact',
'affiliate_realy_want_decline':'Are you sure you want to reject the withdrawal?',
'affiliate_realy_want_accept':'Are you allow to make the user\'s withdrawal?',
'links_realydel':'Are you sure you want to delete the link?',
'links_noname':'Untitled',
'statistics_conversion':'Conversion',
'domains_domain_notavalible':'Domain is busy, please enter another',
'domains_domain_incorrect':'The domain is not entered correctly, or domain zone is not supported',
'deposit_realy_want_decline':'Are you sure you want to reject the withdrawal of deposit?',
'deposit_realy_want_accept':'Do you agree to make a withdrawal to the user?',
'forms_fb_addOption':'Add an option',
'forms_fb_allFieldsRemoved':'All the fields are deleted',
'forms_fb_allowSelect':'Allow the selection',
'forms_fb_autocomplete':'Auto filling',
'forms_fb_button':'The button',
'forms_fb_checkboxGroup':'The group of flags',
'forms_fb_checkboxes':'Flags',
'forms_fb_clearAll':'Clear',
'forms_fb_content':'The contents',
'forms_fb_dateField':'Date field',
'forms_fb_descriptionField':'The description',
'forms_fb_editXML':'XML Editing',
'forms_fb_enableOther':'Include \"Other\"',
'forms_fb_enableOtherMsg':'Allow the users to enter an option not from the list',
'forms_fb_fieldRemoveWarning':'Are you sure you want to delete this field?',
'forms_fb_fileUpload':'Download the file',
'forms_fb_formUpdated':'The form is updated',
'forms_fb_hide':'Edit',
'forms_fb_hidden':'Hidden field',
'forms_fb_labelEmpty':'The label field can not be empty',
'forms_fb_mandatory':'Required',
'forms_fb_maxlength':'The maximum length',
'forms_fb_no':'No',
'forms_fb_on':'Enabled',
'forms_fb_option':'Option',
'forms_fb_optionValuePlaceholder':'The meaning',
'forms_fb_optionEmpty':'Enter the value of the parameter',
'forms_fb_other':'Other',
'forms_fb_paragraph':'Paragraph',
'forms_fb_placeholder':'Placeholder ',
'forms_fb_email':'Enter your email address',
'forms_fb_password':'Enter your password',
'forms_fb_radio':'A switch',
'forms_fb_required':'Necessarily',
'forms_fb_roles':'Access',
'forms_fb_save':'Save',
'forms_fb_selectColor':'Choose the colour',
'forms_fb_size':'The size',
'forms_fb_sm':'Small',
'forms_fb_m':'By the default',
'forms_fb_default':'By the default',
'forms_fb_info':'The information',
'forms_fb_primary':'Basic',
'forms_fb_success':'Successfully',
'forms_fb_warning':'A warning!',
'forms_fb_text':'The text field',
'forms_fb_toggle':'A switch',
'forms_fb_yes':'Yes',
'instabot__del__profile':'Delete profile?',
'instabot__comment__answered':'You have successfully replied to a comment!',
'instabot__del__comment':'Are you sure you want to delete the comment?',
}
/*Time: 0.012303113937378 ms */